export interface Country {
  code: string
  name: string
  region: string
  subRegion: string
  isEU: boolean
  isEEA: boolean
  isOECD: boolean
  isFATF: boolean
}

export const COUNTRIES_CATALOGUE: Country[] = [
  // Europe - EU/EEA
  {
    code: "AT",
    name: "Austria",
    region: "Europe",
    subRegion: "Western Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "BE",
    name: "Belgium",
    region: "Europe",
    subRegion: "Western Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "BG",
    name: "Bulgaria",
    region: "Europe",
    subRegion: "Eastern Europe",
    isEU: true,
    isEEA: true,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "HR",
    name: "Croatia",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: true,
    isEEA: true,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "CY",
    name: "Cyprus",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: true,
    isEEA: true,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "CZ",
    name: "Czech Republic",
    region: "Europe",
    subRegion: "Eastern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "DK",
    name: "Denmark",
    region: "Europe",
    subRegion: "Northern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "EE",
    name: "Estonia",
    region: "Europe",
    subRegion: "Northern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: false,
  },
  {
    code: "FI",
    name: "Finland",
    region: "Europe",
    subRegion: "Northern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "FR",
    name: "France",
    region: "Europe",
    subRegion: "Western Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "DE",
    name: "Germany",
    region: "Europe",
    subRegion: "Western Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "GR",
    name: "Greece",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "HU",
    name: "Hungary",
    region: "Europe",
    subRegion: "Eastern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "IE",
    name: "Ireland",
    region: "Europe",
    subRegion: "Northern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "IT",
    name: "Italy",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "LV",
    name: "Latvia",
    region: "Europe",
    subRegion: "Northern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: false,
  },
  {
    code: "LT",
    name: "Lithuania",
    region: "Europe",
    subRegion: "Northern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: false,
  },
  {
    code: "LU",
    name: "Luxembourg",
    region: "Europe",
    subRegion: "Western Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "MT",
    name: "Malta",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: true,
    isEEA: true,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "NL",
    name: "Netherlands",
    region: "Europe",
    subRegion: "Western Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "PL",
    name: "Poland",
    region: "Europe",
    subRegion: "Eastern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: false,
  },
  {
    code: "PT",
    name: "Portugal",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "RO",
    name: "Romania",
    region: "Europe",
    subRegion: "Eastern Europe",
    isEU: true,
    isEEA: true,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "SK",
    name: "Slovakia",
    region: "Europe",
    subRegion: "Eastern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: false,
  },
  {
    code: "SI",
    name: "Slovenia",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: false,
  },
  {
    code: "ES",
    name: "Spain",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "SE",
    name: "Sweden",
    region: "Europe",
    subRegion: "Northern Europe",
    isEU: true,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  // EEA non-EU
  {
    code: "IS",
    name: "Iceland",
    region: "Europe",
    subRegion: "Northern Europe",
    isEU: false,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "LI",
    name: "Liechtenstein",
    region: "Europe",
    subRegion: "Western Europe",
    isEU: false,
    isEEA: true,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "NO",
    name: "Norway",
    region: "Europe",
    subRegion: "Northern Europe",
    isEU: false,
    isEEA: true,
    isOECD: true,
    isFATF: true,
  },
  // Europe non-EU/EEA
  {
    code: "GB",
    name: "United Kingdom",
    region: "Europe",
    subRegion: "Northern Europe",
    isEU: false,
    isEEA: false,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "CH",
    name: "Switzerland",
    region: "Europe",
    subRegion: "Western Europe",
    isEU: false,
    isEEA: false,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "AD",
    name: "Andorra",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "AL",
    name: "Albania",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "BY",
    name: "Belarus",
    region: "Europe",
    subRegion: "Eastern Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "GI",
    name: "Gibraltar",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "MC",
    name: "Monaco",
    region: "Europe",
    subRegion: "Western Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: true,
  },
  {
    code: "MD",
    name: "Moldova",
    region: "Europe",
    subRegion: "Eastern Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "ME",
    name: "Montenegro",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "MK",
    name: "North Macedonia",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "RS",
    name: "Serbia",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "RU",
    name: "Russia",
    region: "Europe",
    subRegion: "Eastern Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: true,
  },
  {
    code: "SM",
    name: "San Marino",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "TR",
    name: "Turkey",
    region: "Europe",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "UA",
    name: "Ukraine",
    region: "Europe",
    subRegion: "Eastern Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "VA",
    name: "Vatican City",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "XK",
    name: "Kosovo",
    region: "Europe",
    subRegion: "Southern Europe",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  // North America
  {
    code: "US",
    name: "United States",
    region: "Americas",
    subRegion: "North America",
    isEU: false,
    isEEA: false,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "CA",
    name: "Canada",
    region: "Americas",
    subRegion: "North America",
    isEU: false,
    isEEA: false,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "MX",
    name: "Mexico",
    region: "Americas",
    subRegion: "Central America",
    isEU: false,
    isEEA: false,
    isOECD: true,
    isFATF: true,
  },
  // Central America & Caribbean
  {
    code: "AG",
    name: "Antigua and Barbuda",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "BB",
    name: "Barbados",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "BS",
    name: "Bahamas",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "BZ",
    name: "Belize",
    region: "Americas",
    subRegion: "Central America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "CR",
    name: "Costa Rica",
    region: "Americas",
    subRegion: "Central America",
    isEU: false,
    isEEA: false,
    isOECD: true,
    isFATF: false,
  },
  {
    code: "CU",
    name: "Cuba",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "DM",
    name: "Dominica",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "DO",
    name: "Dominican Republic",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "GD",
    name: "Grenada",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "GT",
    name: "Guatemala",
    region: "Americas",
    subRegion: "Central America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "HN",
    name: "Honduras",
    region: "Americas",
    subRegion: "Central America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "HT",
    name: "Haiti",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "JM",
    name: "Jamaica",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "KY",
    name: "Cayman Islands",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "LC",
    name: "Saint Lucia",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "NI",
    name: "Nicaragua",
    region: "Americas",
    subRegion: "Central America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "PA",
    name: "Panama",
    region: "Americas",
    subRegion: "Central America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "PR",
    name: "Puerto Rico",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "SV",
    name: "El Salvador",
    region: "Americas",
    subRegion: "Central America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "VG",
    name: "British Virgin Islands",
    region: "Americas",
    subRegion: "Caribbean",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  // South America
  {
    code: "AR",
    name: "Argentina",
    region: "Americas",
    subRegion: "South America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: true,
  },
  {
    code: "BO",
    name: "Bolivia",
    region: "Americas",
    subRegion: "South America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "BR",
    name: "Brazil",
    region: "Americas",
    subRegion: "South America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: true,
  },
  {
    code: "CL",
    name: "Chile",
    region: "Americas",
    subRegion: "South America",
    isEU: false,
    isEEA: false,
    isOECD: true,
    isFATF: false,
  },
  {
    code: "CO",
    name: "Colombia",
    region: "Americas",
    subRegion: "South America",
    isEU: false,
    isEEA: false,
    isOECD: true,
    isFATF: false,
  },
  {
    code: "EC",
    name: "Ecuador",
    region: "Americas",
    subRegion: "South America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "GY",
    name: "Guyana",
    region: "Americas",
    subRegion: "South America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "PE",
    name: "Peru",
    region: "Americas",
    subRegion: "South America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "PY",
    name: "Paraguay",
    region: "Americas",
    subRegion: "South America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "SR",
    name: "Suriname",
    region: "Americas",
    subRegion: "South America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "UY",
    name: "Uruguay",
    region: "Americas",
    subRegion: "South America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "VE",
    name: "Venezuela",
    region: "Americas",
    subRegion: "South America",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  // Asia Pacific
  {
    code: "AU",
    name: "Australia",
    region: "Oceania",
    subRegion: "Australia and New Zealand",
    isEU: false,
    isEEA: false,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "NZ",
    name: "New Zealand",
    region: "Oceania",
    subRegion: "Australia and New Zealand",
    isEU: false,
    isEEA: false,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "JP",
    name: "Japan",
    region: "Asia",
    subRegion: "Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "KR",
    name: "South Korea",
    region: "Asia",
    subRegion: "Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "CN",
    name: "China",
    region: "Asia",
    subRegion: "Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: true,
  },
  {
    code: "HK",
    name: "Hong Kong",
    region: "Asia",
    subRegion: "Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: true,
  },
  {
    code: "TW",
    name: "Taiwan",
    region: "Asia",
    subRegion: "Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "SG",
    name: "Singapore",
    region: "Asia",
    subRegion: "South-Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: true,
  },
  {
    code: "MY",
    name: "Malaysia",
    region: "Asia",
    subRegion: "South-Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: true,
  },
  {
    code: "TH",
    name: "Thailand",
    region: "Asia",
    subRegion: "South-Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "ID",
    name: "Indonesia",
    region: "Asia",
    subRegion: "South-Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: true,
  },
  {
    code: "PH",
    name: "Philippines",
    region: "Asia",
    subRegion: "South-Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "VN",
    name: "Vietnam",
    region: "Asia",
    subRegion: "South-Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "IN",
    name: "India",
    region: "Asia",
    subRegion: "Southern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: true,
  },
  {
    code: "PK",
    name: "Pakistan",
    region: "Asia",
    subRegion: "Southern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "BD",
    name: "Bangladesh",
    region: "Asia",
    subRegion: "Southern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "LK",
    name: "Sri Lanka",
    region: "Asia",
    subRegion: "Southern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "NP",
    name: "Nepal",
    region: "Asia",
    subRegion: "Southern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "KH",
    name: "Cambodia",
    region: "Asia",
    subRegion: "South-Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "MM",
    name: "Myanmar",
    region: "Asia",
    subRegion: "South-Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "LA",
    name: "Laos",
    region: "Asia",
    subRegion: "South-Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "BN",
    name: "Brunei",
    region: "Asia",
    subRegion: "South-Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "MN",
    name: "Mongolia",
    region: "Asia",
    subRegion: "Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "KP",
    name: "North Korea",
    region: "Asia",
    subRegion: "Eastern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  // Middle East
  {
    code: "AE",
    name: "United Arab Emirates",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: true,
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: true,
  },
  {
    code: "QA",
    name: "Qatar",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "KW",
    name: "Kuwait",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "BH",
    name: "Bahrain",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: true,
  },
  {
    code: "OM",
    name: "Oman",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "IL",
    name: "Israel",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: true,
    isFATF: true,
  },
  {
    code: "JO",
    name: "Jordan",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "LB",
    name: "Lebanon",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "IQ",
    name: "Iraq",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "IR",
    name: "Iran",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "SY",
    name: "Syria",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "YE",
    name: "Yemen",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "PS",
    name: "Palestine",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  // Central Asia
  {
    code: "KZ",
    name: "Kazakhstan",
    region: "Asia",
    subRegion: "Central Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    region: "Asia",
    subRegion: "Central Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "TM",
    name: "Turkmenistan",
    region: "Asia",
    subRegion: "Central Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "TJ",
    name: "Tajikistan",
    region: "Asia",
    subRegion: "Central Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    region: "Asia",
    subRegion: "Central Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "AF",
    name: "Afghanistan",
    region: "Asia",
    subRegion: "Southern Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  // South Caucasus
  {
    code: "GE",
    name: "Georgia",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "AM",
    name: "Armenia",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    region: "Asia",
    subRegion: "Western Asia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  // Africa - North
  {
    code: "EG",
    name: "Egypt",
    region: "Africa",
    subRegion: "Northern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "MA",
    name: "Morocco",
    region: "Africa",
    subRegion: "Northern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "DZ",
    name: "Algeria",
    region: "Africa",
    subRegion: "Northern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "TN",
    name: "Tunisia",
    region: "Africa",
    subRegion: "Northern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "LY",
    name: "Libya",
    region: "Africa",
    subRegion: "Northern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "SD",
    name: "Sudan",
    region: "Africa",
    subRegion: "Northern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  // Africa - Sub-Saharan
  {
    code: "ZA",
    name: "South Africa",
    region: "Africa",
    subRegion: "Southern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: true,
  },
  {
    code: "NG",
    name: "Nigeria",
    region: "Africa",
    subRegion: "Western Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "KE",
    name: "Kenya",
    region: "Africa",
    subRegion: "Eastern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "GH",
    name: "Ghana",
    region: "Africa",
    subRegion: "Western Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "ET",
    name: "Ethiopia",
    region: "Africa",
    subRegion: "Eastern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "TZ",
    name: "Tanzania",
    region: "Africa",
    subRegion: "Eastern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "UG",
    name: "Uganda",
    region: "Africa",
    subRegion: "Eastern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "RW",
    name: "Rwanda",
    region: "Africa",
    subRegion: "Eastern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "SN",
    name: "Senegal",
    region: "Africa",
    subRegion: "Western Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "CI",
    name: "Ivory Coast",
    region: "Africa",
    subRegion: "Western Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "CM",
    name: "Cameroon",
    region: "Africa",
    subRegion: "Middle Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "AO",
    name: "Angola",
    region: "Africa",
    subRegion: "Middle Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "MZ",
    name: "Mozambique",
    region: "Africa",
    subRegion: "Eastern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    region: "Africa",
    subRegion: "Eastern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "ZM",
    name: "Zambia",
    region: "Africa",
    subRegion: "Eastern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "BW",
    name: "Botswana",
    region: "Africa",
    subRegion: "Southern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "NA",
    name: "Namibia",
    region: "Africa",
    subRegion: "Southern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "MU",
    name: "Mauritius",
    region: "Africa",
    subRegion: "Eastern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "SC",
    name: "Seychelles",
    region: "Africa",
    subRegion: "Eastern Africa",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  // Pacific Islands
  {
    code: "FJ",
    name: "Fiji",
    region: "Oceania",
    subRegion: "Melanesia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    region: "Oceania",
    subRegion: "Melanesia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "WS",
    name: "Samoa",
    region: "Oceania",
    subRegion: "Polynesia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "TO",
    name: "Tonga",
    region: "Oceania",
    subRegion: "Polynesia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
  {
    code: "VU",
    name: "Vanuatu",
    region: "Oceania",
    subRegion: "Melanesia",
    isEU: false,
    isEEA: false,
    isOECD: false,
    isFATF: false,
  },
]

export const REGIONS = [...new Set(COUNTRIES_CATALOGUE.map((c) => c.region))].sort()
export const SUB_REGIONS = [...new Set(COUNTRIES_CATALOGUE.map((c) => c.subRegion))].sort()
